package holamundo;

import Clases.ListaImagenes;
import Clases.Panel;
import Clases.Hilo;
import ConexionBD.AppletDAO;
import ConexionBD.ConexionBD;
import TO.EstudianteTO;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author estebanfcv
 */
public class Window extends javax.swing.JApplet {

    private int contador;
    private int tamanio;
    private Hilo hilo;
    private boolean reset;

    /**
     * Initializes the applet Window
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbComenzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbReset = new javax.swing.JButton();
        jlInstrucciones = new javax.swing.JLabel();
        jlInstrucciones2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlCorreo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDescripcion = new javax.swing.JTextArea();
        jbAdelante = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jlMinutos = new javax.swing.JLabel();
        jlSegundos = new javax.swing.JLabel();
        jlSeparador = new javax.swing.JLabel();
        jbFinalizar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jlMensajeError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlConsultaCalificacion = new javax.swing.JLabel();
        jlEmailRegistro = new javax.swing.JLabel();
        jtfEmailRegistro = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jlNombreResultado = new javax.swing.JLabel();
        jtfNombreResultado = new javax.swing.JTextField();
        jlEmailResultado = new javax.swing.JLabel();
        jtfEmailResultado = new javax.swing.JTextField();
        jlFechaResultado = new javax.swing.JLabel();
        jtfFechaResultado = new javax.swing.JTextField();
        jlTiempoResultado = new javax.swing.JLabel();
        jtfTiempoResultado = new javax.swing.JTextField();
        jlRetroalimentacionResultado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaRetroalimentacionResultado = new javax.swing.JTextArea();
        jlCalificacionResultado = new javax.swing.JLabel();
        jtfCalificacionResultado = new javax.swing.JTextField();
        jlMensajeResultado = new javax.swing.JLabel();
        jlMensajeCalificacion = new javax.swing.JLabel();
        jbLimpiar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(1229, 610));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jbComenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/comenzar.png"))); // NOI18N
        jbComenzar.setToolTipText("Comenzar");
        jbComenzar.setMaximumSize(new java.awt.Dimension(32, 32));
        jbComenzar.setMinimumSize(new java.awt.Dimension(32, 32));
        jbComenzar.setPreferredSize(new java.awt.Dimension(32, 32));
        jbComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComenzarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jbReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/restart.png"))); // NOI18N
        jbReset.setMaximumSize(new java.awt.Dimension(32, 32));
        jbReset.setMinimumSize(new java.awt.Dimension(32, 32));
        jbReset.setPreferredSize(new java.awt.Dimension(32, 32));
        jbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResetActionPerformed(evt);
            }
        });

        jlInstrucciones.setText("Instrucciones: A continuacion apareceran los logos de algunos de los programas que se utilizaran");

        jlInstrucciones2.setText("en el curso. Describe con tus propias palabras lo que hayas entendido de cada uno de ellos.");

        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("NOTA: Contesta lo mejor que puedas ya que es una evaluacion, la retroalimentacion podrás");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("consultarla en esta misma ventana. Tienes 10 minutos para responder.");

        jlNombre.setText("Nombre");

        jlCorreo.setText("E-mail");

        jLabel5.setText("Tiempo");

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("Descripcion");

        jtaDescripcion.setColumns(20);
        jtaDescripcion.setRows(5);
        jScrollPane1.setViewportView(jtaDescripcion);

        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/adelante.png"))); // NOI18N
        jbAdelante.setMaximumSize(new java.awt.Dimension(32, 32));
        jbAdelante.setMinimumSize(new java.awt.Dimension(32, 32));
        jbAdelante.setPreferredSize(new java.awt.Dimension(32, 32));
        jbAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdelanteActionPerformed(evt);
            }
        });

        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/atras.png"))); // NOI18N
        jbAtras.setMaximumSize(new java.awt.Dimension(32, 32));
        jbAtras.setMinimumSize(new java.awt.Dimension(32, 32));
        jbAtras.setPreferredSize(new java.awt.Dimension(32, 32));
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        jlMinutos.setText("00");

        jlSegundos.setText("00");

        jlSeparador.setText(":");

        jbFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/finalizar.png"))); // NOI18N
        jbFinalizar.setToolTipText("Finalizar");
        jbFinalizar.setMaximumSize(new java.awt.Dimension(32, 32));
        jbFinalizar.setMinimumSize(new java.awt.Dimension(32, 32));
        jbFinalizar.setPreferredSize(new java.awt.Dimension(32, 32));
        jbFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        jbGuardar.setToolTipText("Guardar");
        jbGuardar.setMaximumSize(new java.awt.Dimension(32, 32));
        jbGuardar.setMinimumSize(new java.awt.Dimension(32, 32));
        jbGuardar.setPreferredSize(new java.awt.Dimension(32, 32));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jlMensajeError.setText("Mensaje de error");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlConsultaCalificacion.setText("Consulta de calificaciones");

        jlEmailRegistro.setText("E-mail de registro");

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jbBuscar.setToolTipText("Buscar");
        jbBuscar.setMaximumSize(new java.awt.Dimension(32, 32));
        jbBuscar.setMinimumSize(new java.awt.Dimension(32, 32));
        jbBuscar.setPreferredSize(new java.awt.Dimension(32, 32));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jlNombreResultado.setText("Nombre");

        jtfNombreResultado.setEditable(false);
        jtfNombreResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreResultadoActionPerformed(evt);
            }
        });

        jlEmailResultado.setText("E-mail");

        jtfEmailResultado.setEditable(false);

        jlFechaResultado.setText("Fecha");

        jtfFechaResultado.setEditable(false);

        jlTiempoResultado.setText("Tiempo");

        jtfTiempoResultado.setEditable(false);

        jlRetroalimentacionResultado.setText("Retroalimentacion");

        jtaRetroalimentacionResultado.setEditable(false);
        jtaRetroalimentacionResultado.setColumns(20);
        jtaRetroalimentacionResultado.setRows(5);
        jScrollPane2.setViewportView(jtaRetroalimentacionResultado);

        jlCalificacionResultado.setText("Calificacion");

        jtfCalificacionResultado.setEditable(false);
        jtfCalificacionResultado.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jtfCalificacionResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCalificacionResultadoActionPerformed(evt);
            }
        });

        jlMensajeResultado.setText("Mensaje de error");

        jlMensajeCalificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMensajeCalificacion.setText("Mensaje calificacion");

        jbLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        jbLimpiar.setToolTipText("Limpiar");
        jbLimpiar.setMaximumSize(new java.awt.Dimension(32, 32));
        jbLimpiar.setMinimumSize(new java.awt.Dimension(32, 32));
        jbLimpiar.setPreferredSize(new java.awt.Dimension(32, 32));
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jLabel7.setText("Software realizado por Esteban Chaparro 2015");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jbReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jlMinutos)
                        .addGap(6, 6, 6)
                        .addComponent(jlSeparador)
                        .addGap(6, 6, 6)
                        .addComponent(jlSegundos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlInstrucciones)
                            .addComponent(jlInstrucciones2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombre)
                                    .addComponent(jlCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(jbComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(jbFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jlMensajeError)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlConsultaCalificacion)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlNombreResultado)
                                            .addComponent(jlEmailResultado)
                                            .addComponent(jlFechaResultado)
                                            .addComponent(jlCalificacionResultado))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jtfFechaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(71, 71, 71)
                                                    .addComponent(jlTiempoResultado)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jtfTiempoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                                .addComponent(jtfEmailResultado)
                                                .addComponent(jtfNombreResultado))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jlMensajeCalificacion)
                                                    .addComponent(jtfCalificacionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jlMensajeResultado))
                                        .addGap(161, 161, 161))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlEmailRegistro)
                                        .addGap(24, 24, 24)
                                        .addComponent(jtfEmailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlRetroalimentacionResultado)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane2)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlConsultaCalificacion)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmailRegistro)
                    .addComponent(jtfEmailRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlMensajeResultado)
                .addGap(8, 8, 8)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreResultado)
                    .addComponent(jtfNombreResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmailResultado)
                    .addComponent(jtfEmailResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFechaResultado)
                    .addComponent(jtfFechaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTiempoResultado)
                    .addComponent(jtfTiempoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jlRetroalimentacionResultado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCalificacionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCalificacionResultado))
                .addGap(18, 18, 18)
                .addComponent(jlMensajeCalificacion)
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addComponent(jbReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jlMinutos)
                            .addComponent(jlSeparador)
                            .addComponent(jlSegundos))
                        .addGap(16, 16, 16)
                        .addComponent(jlInstrucciones)
                        .addGap(5, 5, 5)
                        .addComponent(jlInstrucciones2)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jlNombre)
                                .addGap(10, 10, 10)
                                .addComponent(jlCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jtfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jbComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(jbFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jlMensajeError)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComenzarActionPerformed
        reset = false;
        if (jtfNombre.getText().trim().isEmpty()) {
            jlMensajeError.setText("Favor de escribir su nombre");
            jlMensajeError.setForeground(Color.red);
            return;
        }
        if (jtfCorreo.getText().trim().isEmpty()) {
            jlMensajeError.setText("Favor de escribir su E-mail");
            jlMensajeError.setForeground(Color.red);
            return;
        }
//        if (!util.Util.validarEmail(jtfCorreo.getText())) {
//            jlMensajeError.setText("El correo no es válido");
//            jlMensajeError.setForeground(Color.red);
//            return;
//        }
        if (AppletDAO.obtenerEstudiante(jtfCorreo.getText()).getId() > 0) {
            jlMensajeError.setText("El usuario ya está registrado");
            jlMensajeError.setForeground(Color.red);
            return;
        }
        jbComenzar.setEnabled(false);
        jbAdelante.setEnabled(true);
        jbAtras.setEnabled(true);
        jbFinalizar.setEnabled(true);
        jbGuardar.setEnabled(true);
        jbReset.setEnabled(true);
        jtfNombre.setEditable(false);
        jtfCorreo.setEditable(false);
        pintarPanel();
        hilo = new Hilo(this);
        Thread thread = new Thread(hilo);
        thread.start();
    }//GEN-LAST:event_jbComenzarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // Pimer metodo en activarse, aqui se inicializaran los valores
        ConexionBD.setConexion();
        jbComenzar.setEnabled(true);
        jbAdelante.setEnabled(false);
        jbAtras.setEnabled(false);
        jbFinalizar.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbReset.setEnabled(false);
        jtfNombre.setEditable(true);
        jtfCorreo.setEditable(true);
        contador = 0;
        jtfNombre.setText("");
        jlMinutos.setText("00");
        jlSegundos.setText("00");
        jtfCorreo.setText("");
        ListaImagenes.armarListaImagenes();
        tamanio = ListaImagenes.getTamanio();
        jlMensajeCalificacion.setText("");
        jlMensajeResultado.setText("");
        jlMensajeError.setText("");
    }//GEN-LAST:event_formComponentShown

    private void jbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResetActionPerformed
        reset = true;
        hilo.setCorriendo(false);
        ListaImagenes.armarListaImagenes();
        jbComenzar.setEnabled(true);
        jbAdelante.setEnabled(false);
        jbAtras.setEnabled(false);
        jbFinalizar.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbReset.setEnabled(false);
        jtfNombre.setEditable(true);
        jtfCorreo.setEditable(true);
        jtfNombre.setText("");
        jtfCorreo.setText("");
        jlMinutos.setText("00");
        jlSegundos.setText("00");
        contador = 0;
        jlMensajeError.setText("");
    }//GEN-LAST:event_jbResetActionPerformed

    public void abrirVentana() {
        JOptionPane.showMessageDialog(null, "Se acabó el tiempo");
        hilo.reanudarHilo();
        hilo.setCorriendo(false);
        insertarDatos();
    }

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        try {
            contador--;
            if (contador < 0) {
                contador = tamanio - 1;
            }
            pintarPanel();
            jtaDescripcion.setText(ListaImagenes.getDescripcion(contador));
        } catch (Exception e) {
            jLabel2.setText(e.getMessage());
        }
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void jbAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdelanteActionPerformed
        try {
            contador++;
            if (contador == tamanio) {
                contador = 0;
            }
            pintarPanel();
            jtaDescripcion.setText(ListaImagenes.getDescripcion(contador));
        } catch (Exception e) {
            jLabel2.setText(e.getMessage());
        }
    }//GEN-LAST:event_jbAdelanteActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        ListaImagenes.setDescripcion(contador, jtaDescripcion.getText());
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarActionPerformed
        reset = true;
        hilo.suspenderHilo();
        boolean vacio = false;
        for (int i = 0; i < tamanio; i++) {
            if (ListaImagenes.getDescripcion(i).isEmpty()) {
                vacio = true;
                break;
            }
        }
        if (vacio) {
            String titulo = "Notificación";
            String mensaje = "¿Desea finalizar la prueba ? \n Dejo preguntas sin contestar";
            int x = JOptionPane.showConfirmDialog(null, mensaje, titulo, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (x == 0) { // si
                hilo.reanudarHilo();
                hilo.setCorriendo(false);
                insertarDatos();
            } else { // no
                hilo.reanudarHilo();
            }
        } else {
            hilo.reanudarHilo();
            hilo.setCorriendo(false);
            insertarDatos();
        }
    }//GEN-LAST:event_jbFinalizarActionPerformed

    private void jtfNombreResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreResultadoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        if (jtfEmailRegistro.getText().trim().isEmpty()) {
            jlMensajeResultado.setText("Favor de escribir su E-mail");
            jlMensajeResultado.setForeground(Color.red);
            return;
        }
        if (!util.Util.validarEmail(jtfEmailRegistro.getText())) {
            jlMensajeResultado.setText("El correo no es válido");
            jlMensajeResultado.setForeground(Color.red);
            return;
        }
        EstudianteTO estudiante = AppletDAO.obtenerEstudiante(jtfEmailRegistro.getText());
        if (estudiante.getId() == 0) {
            jlMensajeResultado.setText("El usuario no existe");
            jlMensajeResultado.setForeground(Color.red);
        } else if (estudiante.getCalificacion() == 0 && estudiante.getRetroalimentacion().isEmpty()) {
            jlMensajeResultado.setText("Tu profesor todavía no te evalua. Intentalo más tarde.");
            jlMensajeResultado.setForeground(Color.red);
        } else {
            jlMensajeResultado.setText("Se encontró la siguiente información en el sistema");
            jlMensajeResultado.setForeground(Color.green);
            jtfEmailRegistro.setEditable(false);
            jtfNombreResultado.setText(estudiante.getNombre());
            jtfEmailResultado.setText(estudiante.getEmail());
            jtfFechaResultado.setText(estudiante.getFecha().toString());
            jtfTiempoResultado.setText(estudiante.getTiempo());
            jtaRetroalimentacionResultado.setText(estudiante.getRetroalimentacion());
            jtfCalificacionResultado.setText(String.valueOf(estudiante.getCalificacion()));
            if (estudiante.getCalificacion() >= 9) {
                jtfCalificacionResultado.setForeground(Color.GREEN);
                jlMensajeCalificacion.setText("Muchas felicidades se ve que entendiste el tema.");
            } else if (estudiante.getCalificacion() >= 7 && estudiante.getCalificacion() < 9) {
                jtfCalificacionResultado.setForeground(Color.ORANGE);
                jlMensajeCalificacion.setText("Esta bien aunque pudes mejorar para futuras pruebas.");
            } else {
                jtfCalificacionResultado.setForeground(Color.RED);
                jlMensajeCalificacion.setText("Necesitas mayor dedicación en tus estudios.");
            }
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        jlMensajeCalificacion.setText("");
        jlMensajeResultado.setText("");
        jtfEmailRegistro.setEditable(true);
        jtfNombreResultado.setText("");
        jtfEmailResultado.setText("");
        jtfFechaResultado.setText("");
        jtfTiempoResultado.setText("");
        jtaRetroalimentacionResultado.setText("");
        jtfCalificacionResultado.setText("");
        jtfEmailRegistro.setText("");
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jtfCalificacionResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCalificacionResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCalificacionResultadoActionPerformed

    private void insertarDatos() {
        EstudianteTO estudiante = new EstudianteTO();
        estudiante.setNombre(jtfNombre.getText());
        estudiante.setEmail(jtfCorreo.getText());
        estudiante.setFecha(new Date());
        estudiante.setTiempo(jlMinutos.getText() + ":" + jlSegundos.getText());
        int id = AppletDAO.insertarEstudiante(estudiante);
        if (id == 0) {
            jlMensajeError.setText("Hubo un error al insertar los datos del estudiante.");
            jlMensajeError.setForeground(Color.red);
            return;
        }
        if (!AppletDAO.insertarRespuestas(ListaImagenes.getLista(), id)) {
            jlMensajeError.setText("Hubo un error al insertar las resupuestas.");
            jlMensajeError.setForeground(Color.red);
            return;
        }
        jlMensajeError.setText("La inserción se realizó con éxito.");
        jlMensajeError.setForeground(Color.green);
    }

    private void pintarPanel() {
        jPanel1.removeAll();
        Panel p = new Panel(ListaImagenes.getNombreImagen(contador));
        jPanel1.add(p, BorderLayout.CENTER);
        jPanel1.repaint();
    }

    public JLabel getJlMinutos() {
        return jlMinutos;
    }

    public void setJlMinutos(JLabel jlMinutos) {
        this.jlMinutos = jlMinutos;
    }

    public JLabel getJlSegundos() {
        return jlSegundos;
    }

    public void setJlSegundos(JLabel jlSegundos) {
        this.jlSegundos = jlSegundos;
    }

    public boolean isReset() {
        return reset;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbComenzar;
    private javax.swing.JButton jbFinalizar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbReset;
    private javax.swing.JLabel jlCalificacionResultado;
    private javax.swing.JLabel jlConsultaCalificacion;
    private javax.swing.JLabel jlCorreo;
    private javax.swing.JLabel jlEmailRegistro;
    private javax.swing.JLabel jlEmailResultado;
    private javax.swing.JLabel jlFechaResultado;
    private javax.swing.JLabel jlInstrucciones;
    private javax.swing.JLabel jlInstrucciones2;
    private javax.swing.JLabel jlMensajeCalificacion;
    private javax.swing.JLabel jlMensajeError;
    private javax.swing.JLabel jlMensajeResultado;
    private javax.swing.JLabel jlMinutos;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreResultado;
    private javax.swing.JLabel jlRetroalimentacionResultado;
    private javax.swing.JLabel jlSegundos;
    private javax.swing.JLabel jlSeparador;
    private javax.swing.JLabel jlTiempoResultado;
    private javax.swing.JTextArea jtaDescripcion;
    private javax.swing.JTextArea jtaRetroalimentacionResultado;
    private javax.swing.JTextField jtfCalificacionResultado;
    private javax.swing.JTextField jtfCorreo;
    private javax.swing.JTextField jtfEmailRegistro;
    private javax.swing.JTextField jtfEmailResultado;
    private javax.swing.JTextField jtfFechaResultado;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfNombreResultado;
    private javax.swing.JTextField jtfTiempoResultado;
    // End of variables declaration//GEN-END:variables
}
