package ventana;

import holamundo.Fondo;
import TO.EstudianteTO;
import TO.RespuestaTO;
import ficheros.Fichero;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import util.Util;

/**
 *
 * @author estebanfcv
 */
public class Ventana extends javax.swing.JFrame {

    private List<EstudianteTO> listaEstudiantes;
    private List<RespuestaTO> listaRespuestas;
    private EstudianteTO estudiante = new EstudianteTO();
    private RespuestaTO respuesta = new RespuestaTO();
    private final Map<String, EstudianteTO> mapaEstudiantes = new LinkedHashMap<String, EstudianteTO>();
    private final Map<String, RespuestaTO> mapaRespuestas = new LinkedHashMap<String, RespuestaTO>();

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAlumno = new javax.swing.JLabel();
        comboAlumno = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboPregunta = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoRespuesta = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoCalificacion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        campoCalificacion = new javax.swing.JTextField();
        bGuardar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();
        mensajeError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textoFecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textoTiempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jlAlumno.setText("E-mail");

        comboAlumno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Seleccione---",}));
        comboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setText("Pregunta");

        comboPregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Seleccione---"}));
        comboPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPreguntaActionPerformed(evt);
            }
        });

        jLabel2.setText("Respuesta");

        textoRespuesta.setEditable(false);
        textoRespuesta.setColumns(20);
        textoRespuesta.setRows(5);
        jScrollPane1.setViewportView(textoRespuesta);

        jLabel3.setText("Retroalimentación");

        textoCalificacion.setColumns(20);
        textoCalificacion.setRows(5);
        jScrollPane2.setViewportView(textoCalificacion);

        jLabel4.setText("Calificación");

        campoCalificacion.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        campoCalificacion.setText("0.0");
        campoCalificacion.setMinimumSize(new java.awt.Dimension(86, 27));
        campoCalificacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                campoCalificacionMouseMoved(evt);
            }
        });

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        bGuardar.setToolTipText("Guardar");
        bGuardar.setMaximumSize(new java.awt.Dimension(32, 32));
        bGuardar.setMinimumSize(new java.awt.Dimension(32, 32));
        bGuardar.setPreferredSize(new java.awt.Dimension(32, 32));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/limpiar.png"))); // NOI18N
        bLimpiar.setToolTipText("Limpiar");
        bLimpiar.setMaximumSize(new java.awt.Dimension(32, 32));
        bLimpiar.setMinimumSize(new java.awt.Dimension(32, 32));
        bLimpiar.setPreferredSize(new java.awt.Dimension(32, 32));
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        mensajeError.setText("Mensaje Error");

        jLabel5.setText("Nombre");

        textoNombre.setEditable(false);

        jLabel6.setText("Fecha");

        textoFecha.setEditable(false);
        textoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoFechaActionPerformed(evt);
            }
        });

        jLabel7.setText("Tiempo");

        textoTiempo.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jlAlumno)
                        .addGap(37, 37, 37)
                        .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)
                        .addComponent(textoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50)
                        .addComponent(campoCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(mensajeError)))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlAlumno)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campoCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mensajeError))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlumnoActionPerformed
        // TODO add your handling code here:
        String opcion = comboAlumno.getSelectedItem().toString();
        System.out.println(opcion);
        comboPregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"---Seleccione---"}));
        if (!opcion.equals("---Seleccione---")) {
            bGuardar.setEnabled(true);
            textoCalificacion.setEditable(true);
            campoCalificacion.setEditable(true);
            estudiante = mapaEstudiantes.get(opcion);
            textoNombre.setText(estudiante.getNombre());
            textoFecha.setText(new SimpleDateFormat("dd/MM/yyyy").format(estudiante.getFecha()));
            textoTiempo.setText(estudiante.getTiempo());
            listaRespuestas = Fichero.obtenerRespuestasEstudiante(estudiante.getId());
            for (RespuestaTO r : listaRespuestas) {
                comboPregunta.addItem(r.getPregunta());
                mapaRespuestas.put(r.getPregunta(), r);
            }
        } else {
            textoNombre.setText("");
            textoFecha.setText("");
            textoTiempo.setText("");
            bGuardar.setEnabled(false);
            textoCalificacion.setText("");
            campoCalificacion.setText("0.0");
            textoCalificacion.setEditable(false);
            campoCalificacion.setEditable(false);

        }
    }//GEN-LAST:event_comboAlumnoActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Fondo f = new Fondo();
        this.add(f, BorderLayout.CENTER);
        this.repaint();
        Util.armarListaContadores();
        mensajeError.setText("");
        listaEstudiantes = Fichero.obtenerEstudiantes();
        for (EstudianteTO e : listaEstudiantes) {
            mapaEstudiantes.put(e.getEmail(), e);
            comboAlumno.addItem(e.getEmail());
        }
        bGuardar.setEnabled(false);
        textoCalificacion.setEditable(false);
        campoCalificacion.setEditable(false);
        campoCalificacion.setForeground(Color.RED);
    }//GEN-LAST:event_formComponentShown

    private void comboPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPreguntaActionPerformed
        String opcion = comboPregunta.getSelectedItem().toString();
        System.out.println(opcion);
        if (!opcion.equals("---Seleccione---")) {
            respuesta = mapaRespuestas.get(opcion);
            textoRespuesta.setText(respuesta.getRespuesta());
        } else {
            textoRespuesta.setText("");
        }
    }//GEN-LAST:event_comboPreguntaActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        textoNombre.setText("");
        textoRespuesta.setText("");
        textoCalificacion.setText("");
        textoFecha.setText("");
        textoTiempo.setText("");
        campoCalificacion.setText("0.0");
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if (textoCalificacion.getText().trim().isEmpty()) {
            mensajeError.setText("Favor de escribir su retroalimentación.");
            mensajeError.setForeground(Color.red);
            return;
        }
        if (Util.isNumero(campoCalificacion.getText()) <= 0 || Util.isNumero(campoCalificacion.getText()) > 10) {
            mensajeError.setText("La calificación debe ser mayor a cero y menor a 10");
            mensajeError.setForeground(Color.red);
            return;
        }
        estudiante.setCalificacion(new Float(campoCalificacion.getText()));
        estudiante.setRetroalimentacion(textoCalificacion.getText());
        if (Fichero.modificarCalificacionEstudiante(estudiante)) {
            mensajeError.setText("La operación se realizó con exito.");
            mensajeError.setForeground(Color.green);
        } else {
            mensajeError.setText("Hubo un error.");
            mensajeError.setForeground(Color.red);
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void textoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoFechaActionPerformed
    }//GEN-LAST:event_textoFechaActionPerformed

    private void campoCalificacionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCalificacionMouseMoved
        // TODO add your handling code here:
        campoCalificacion.setText(String.valueOf(Util.isNumero(campoCalificacion.getText())));
        float f = new Float(campoCalificacion.getText());
        if (f >= 9) {
            campoCalificacion.setForeground(Color.GREEN);
        } else if (f >= 7 && f < 9) {
            campoCalificacion.setForeground(Color.ORANGE);
        } else {
            campoCalificacion.setForeground(Color.RED);
        }
    }//GEN-LAST:event_campoCalificacionMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JTextField campoCalificacion;
    private javax.swing.JComboBox comboAlumno;
    private javax.swing.JComboBox comboPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlAlumno;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JTextArea textoCalificacion;
    private javax.swing.JTextField textoFecha;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextArea textoRespuesta;
    private javax.swing.JTextField textoTiempo;
    // End of variables declaration//GEN-END:variables
}
